plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.protobuf' version '0.9.5'
}

group = 'com.zos'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
}

def grpcVersion = '1.70.0'

dependencies {
    implementation project(':proto')
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	
	implementation 'org.slf4j:slf4j-api'
	// Source: https://mvnrepository.com/artifact/io.github.nbaars/paseto4j-version4
	implementation 'io.github.nbaars:paseto4j-version4:2024.3'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
	implementation 'org.springframework.security:spring-security-crypto'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'org.postgresql:postgresql'
	// Standard JCA/JCE provider and low-level APIs
    implementation 'org.bouncycastle:bcprov-jdk18on:1.83'
    // Optional: For PKIX/CMS/OCSP/PKCS support
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.83'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation "io.grpc:grpc-stub:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-netty-shaded:${grpcVersion}"
    // Source: https://mvnrepository.com/artifact/org.testcontainers/postgresql
	testImplementation "org.testcontainers:testcontainers-postgresql:2.0.4"
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'com.h2database:h2'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.31.1"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.76.0"
        }
    }
    generateProtoTasks {
        ofSourceSet('main').configureEach {
            plugins {
                grpc {}
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs += [
                "$buildDir/generated/sources/proto/main/java",
                "$buildDir/generated/sources/proto/main/grpc",
                "$buildDir/proto/main/java",
                "$buildDir/proto/main/grpc"
            ]
        }
    }
}

tasks.named("compileJava") {
    dependsOn tasks.named("generateProto")
}

tasks.named('test') {
	useJUnitPlatform()

	testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed"
    }
}
