spring.application.name=home
auth.service.base-url=http://auth:8080
logging.level.com.zos.home.service.AuthClientService=DEBUG
logging.level.org.springframework.web.reactive.function.client=TRACE
logging.level.reactor.netty.http.client=DEBUG