spring.application.name=auth
app.token.secret=SECRET_SECRET_SECRET_SECRET_
# some text to describe token
app.token.footer=POC-PASETO
app.nonce=0000000000000000000000000000000000000000000000000000000000000000
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.server.port=8081
spring.security.user.name=admin
spring.security.user.password=admin


