plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

repositories {
    mavenCentral()
}

def grpcVersion = '1.70.0'
def protobufVersion = '4.29.3'

dependencies {
    api "io.grpc:grpc-stub:${grpcVersion}"
    api "io.grpc:grpc-protobuf:${grpcVersion}"
    api "com.google.protobuf:protobuf-java:${protobufVersion}"

    // Sometimes needed because generated gRPC Java references javax.annotation.Generated
    compileOnly 'org.apache.tomcat:annotations-api:6.0.53'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }

    generateProtoTasks {
        all().configureEach {
            plugins {
                grpc {}
            }
        }
    }
}